server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000 #ms
        response-timeout: 30s
      # route
      # circuit breaker
      discovery:
        locator:
          # dynamic routing
          enabled: false
          lower-case-service-id: true
      # static routing
      routes:
        - id : module-one
          uri : lb://module-one
          predicates:
            - Path=/modOne/**
          filters:
#            - StripPrefix=1
            - name : CircuitBreaker
              args :
                name : feignThree
                fallbackUri: forward:/fallback/reply
        - id : module-two
          uri : lb://module-two
          predicates:
            - Path=/modTwo/**
        - id : module-three
          uri : lb://module-three
          predicates:
            - Path=/modThree/**
      default-filters:
        - AddRequestHeader=X-Gateway, api-gateway
      # CORS
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            #Front(or Client)

            allowed-origins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowed-methods:
              - GET
              - POST
              - OPTIONS
            allowed-headers: "*"
            exposed-headers: "*"
            allow-credentials: true

#resilience4j:
#  circuitbreaker:
#    instances:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#actuator
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    gateway:
      enabled: true
#log
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
